default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  host: mysql
  port: 3306
  username: root
  password:

development:
  <<: *default
  database: RodauthMysql_development

test:
  <<: *default
  database: RodauthMysql_test

production:
  <<: *default
  database: RodauthMysql_production
  username: RodauthMysql
  password: <%= ENV['RODAUTHMYSQL_DATABASE_PASSWORD'] %>
